---
title: "Results"
author: "Guy Taseski and Will Cornwell"
date: "September 26, 2016"
output: html_document
---

#STARTUP crap

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
read_csv("mass_output.csv") %>%
  filter(!is.na(species)) -> mass_df
```

# RDMC vs Tissue Density

```{r}
#Makes graphs
filter(mass_df, !RDMC > 1) -> Plot_TD_RDMC
hist(Plot_TD_RDMC$RDMC)
N<-ggplot(Plot_TD_RDMC, aes(x = RDMC, y = density, colour = species)) + geom_point() + geom_abline()
ggplotly(N)
#Summary_STATS
lm_RDMC_TD<-lm(Plot_TD_RDMC$RDMC ~ Plot_TD_RDMC$density)
summary(lm_RDMC_TD)
```

# Trends in Density across species

Here is some text about what the results actually are.  

Here is a plot.

```{r,echo=FALSE,eval=FALSE}
group_by(mass_df,species) %>%
summarize(
          som.median=median(som),
          density.mean=mean(density,na.rm=TRUE),
          som.quant1=quantile(som,0.5)-quantile(som,0.1),
          som.quant2=quantile(som,0.9)-quantile(som,0.5),
          density.se=sd(density,na.rm=TRUE)/sqrt(sum(!is.na(density))),
          smc.median=median(smc),
          smc.quant1=quantile(smc,0.5)-quantile(smc,0.1),
          smc.quant2=quantile(smc,0.9)-quantile(smc,0.5)
          )->temp    


ggplot(temp,aes(x=som.median,y=density.mean,col=species))+
  geom_point()+
  geom_errorbarh(aes(xmin=som.median-som.quant1,xmax=som.median+som.quant2,y=density.mean))+
  geom_errorbar(aes(ymin=density.mean-density.se,ymax=density.mean+density.se))+
  theme_bw()+
  scale_x_log10(breaks=c(1:10))+ 
  theme(legend.text=element_text(size=7))->gg
gg
```


Here is some statistical analysis

```{r}
#Transformations
mass_df$log_density <- log10(mass_df$density) 
mass_df$sqrt_density <- sqrt(mass_df$density)

qqnorm(mass_df$density)
qqnorm(mass_df$log_density)
qqnorm(mass_df$sqrt_density)

fart <- lm(mass_df$som ~ mass_df$sqrt_density)
anova(fart)
summary(fart)
```

# Trends in SRL across species




